k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 07b7a6f5-6f10-5eaa-b69d-f5ad28cfe19b
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifests
  cluster_info:
    cluster_id: 56e6c599-9811-5895-9af1-435205c89953
    cluster_name: AES Smoke Tests - Helm
- manifest_path: /manifests
  cluster_info:
    cluster_id: 56e6c599-9811-5895-9af1-435205c89953
    cluster_name: Alice Wasko's smoketest cluster
