k8s_config:
- manifest_path: /manifest
  cluster_info:
    cluster_id: 24821ef5-62a9-59ad-8a52-3bcd1e3a8cb9
    cluster_name: Jose de la Mora's cluster
- manifest_path: /manifest
  cluster_info:
    cluster_id: fc049469-4e71-5d4a-89a6-e6be6f8e7d00
    cluster_name: Staging
- manifest_path: /manifest
  cluster_info:
    cluster_id: aaf03b1e-02b5-52f9-8ea5-0e90586c5359
    cluster_name: Cluster 001
- manifest_path: /manifest
  cluster_info:
    cluster_id: 9285f4f6-6de7-5aab-8490-55d68611cc39
    cluster_name: test-023
